final List<String> categories = [
  // CHD
  'CHD_WEBSITES', // 0
  'CHD_VIDEOS', // 1
  'CHD_ARTICLES', // 2
  'CHD_MEDICATIONS', // 3
  // CHILD CARE
  'CHILD_CARE_FORMULA_MIXES', // 4
  'CHILD_CARE_MEDICATION', // 5
  'CHILD_CARE_DRAIN_CARE', // 6
  'CHILD_CARE_WOUND_CARE', // 7
  // SPIRITUAL
  'SP_DEVOTIONALS', // 8
  'SP_RESOURCES', // 9
  // HOSPITAL HELPLINE
  'HOSPITAL_HELPLINE_WEBLINKS', // 10
  'HOSPITAL_HELPLINE_AREA_MAP', // 11
  'HOSPITAL_HELPLINE_SHOWERS', // 12
  'HOSPITAL_HELPLINE_CAFETERIA_MENU', // 13
  //    Caregiver support
  'CAREGIVER_SUPPORT_SUPPORT_GROUPS', // 14
  // CHILD CARE INFORMATION
  'CHILD_CARE_INFORMATION_ARTICLES', // 15
];
